//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tao_Bot_Maker.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tao_Bot_Maker.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        internal static string ButtonAdd {
            get {
                return ResourceManager.GetString("ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add action.
        /// </summary>
        internal static string ButtonAddAction {
            get {
                return ResourceManager.GetString("ButtonAddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unassigned.
        /// </summary>
        internal static string ButtonKeyUnassigned {
            get {
                return ResourceManager.GetString("ButtonKeyUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search image.
        /// </summary>
        internal static string ButtonSearchImage {
            get {
                return ResourceManager.GetString("ButtonSearchImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select image.
        /// </summary>
        internal static string ButtonSelectImage {
            get {
                return ResourceManager.GetString("ButtonSelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiting for input.
        /// </summary>
        internal static string ButtonWaitForInput {
            get {
                return ResourceManager.GetString("ButtonWaitForInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fast.
        /// </summary>
        internal static string ComboBoxSpeedFast {
            get {
                return ResourceManager.GetString("ComboBoxSpeedFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Medium.
        /// </summary>
        internal static string ComboBoxSpeedMedium {
            get {
                return ResourceManager.GetString("ComboBoxSpeedMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slow.
        /// </summary>
        internal static string ComboBoxSpeedSlow {
            get {
                return ResourceManager.GetString("ComboBoxSpeedSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinates.
        /// </summary>
        internal static string Coordinates {
            get {
                return ResourceManager.GetString("Coordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ({0},{1}).
        /// </summary>
        internal static string CoordinatesFormat {
            get {
                return ResourceManager.GetString("CoordinatesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid action.
        /// </summary>
        internal static string ErrorMessageCaptionInvalidAction {
            get {
                return ResourceManager.GetString("ErrorMessageCaptionInvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action corrupted, changes needs to be made to be executed..
        /// </summary>
        internal static string ErrorMessageCorruptedAction {
            get {
                return ResourceManager.GetString("ErrorMessageCorruptedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to load sequence : &quot;{0}&quot;. File might be corrupted..
        /// </summary>
        internal static string ErrorMessageCorruptedSequenceFile {
            get {
                return ResourceManager.GetString("ErrorMessageCorruptedSequenceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence name cannot be empty..
        /// </summary>
        internal static string ErrorMessageEmptyFieldSequence {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyFieldSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text to type cannot be empty..
        /// </summary>
        internal static string ErrorMessageEmptyFieldTextToType {
            get {
                return ResourceManager.GetString("ErrorMessageEmptyFieldTextToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence name cannot be empty..
        /// </summary>
        internal static string ErrorMessageEmptySequenceName {
            get {
                return ResourceManager.GetString("ErrorMessageEmptySequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to load sequence &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorMessageFailToLoadSequence {
            get {
                return ResourceManager.GetString("ErrorMessageFailToLoadSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File not found at : &quot;{0}&quot;.
        /// </summary>
        internal static string ErrorMessageFileNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} : {1}.
        /// </summary>
        internal static string ErrorMessageFormat {
            get {
                return ResourceManager.GetString("ErrorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid action at position {0}..
        /// </summary>
        internal static string ErrorMessageInvalidActionAtIndex {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidActionAtIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Value of &quot;{0}&quot; must be between {1} and {2}..
        /// </summary>
        internal static string ErrorMessageInvalidIntervalFor {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidIntervalFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repeat count cannot be {0}, and must be between {1} and {2}..
        /// </summary>
        internal static string ErrorMessageInvalidRepeatCount {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidRepeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Typing speed must be between {0} and {1}..
        /// </summary>
        internal static string ErrorMessageInvalidTypingSpeed {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidTypingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid value for &quot;{0}&quot;.
        /// </summary>
        internal static string ErrorMessageInvalidValueFor {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidValueFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to copy the file..
        /// </summary>
        internal static string ErrorMessageUnableToCopyFile {
            get {
                return ResourceManager.GetString("ErrorMessageUnableToCopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to rename and copy the file..
        /// </summary>
        internal static string ErrorMessageUnableToRenameAndCopyFile1 {
            get {
                return ResourceManager.GetString("ErrorMessageUnableToRenameAndCopyFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to replace the file..
        /// </summary>
        internal static string ErrorMessageUnableToReplaceFile {
            get {
                return ResourceManager.GetString("ErrorMessageUnableToReplaceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum wait time cannot be less than minimum wait time..
        /// </summary>
        internal static string ErrorMessageWaitActionInvalidMaximumWait {
            get {
                return ResourceManager.GetString("ErrorMessageWaitActionInvalidMaximumWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum wait time cannot be less than 0..
        /// </summary>
        internal static string ErrorMessageWaitActionInvalidMinimumWait {
            get {
                return ResourceManager.GetString("ErrorMessageWaitActionInvalidMinimumWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tao&apos;s Bot Maker.
        /// </summary>
        internal static string FormTitleMain {
            get {
                return ResourceManager.GetString("FormTitleMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add action.
        /// </summary>
        internal static string FormTitleNewAction {
            get {
                return ResourceManager.GetString("FormTitleNewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save sequence.
        /// </summary>
        internal static string FormTitleSaveSequence {
            get {
                return ResourceManager.GetString("FormTitleSaveSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string FormTitleSettings {
            get {
                return ResourceManager.GetString("FormTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expiration.
        /// </summary>
        internal static string ImageActionExpiration {
            get {
                return ResourceManager.GetString("ImageActionExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image name.
        /// </summary>
        internal static string ImageActionImageName {
            get {
                return ResourceManager.GetString("ImageActionImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image.
        /// </summary>
        internal static string ImageActionName {
            get {
                return ResourceManager.GetString("ImageActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Threshold.
        /// </summary>
        internal static string ImageActionThreshold {
            get {
                return ResourceManager.GetString("ImageActionThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search image : &quot;{0}&quot; between coordinates : {1} and {2} for {3} ms..
        /// </summary>
        internal static string ImageActionToString {
            get {
                return ResourceManager.GetString("ImageActionToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Executing action : {0}..
        /// </summary>
        internal static string InfoMessageExecuteAction {
            get {
                return ResourceManager.GetString("InfoMessageExecuteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancelling execution..
        /// </summary>
        internal static string InfoMessageExecutionCancelled {
            get {
                return ResourceManager.GetString("InfoMessageExecutionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ending execution..
        /// </summary>
        internal static string InfoMessageExecutionComplete {
            get {
                return ResourceManager.GetString("InfoMessageExecutionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pausing execution..
        /// </summary>
        internal static string InfoMessageExecutionPaused {
            get {
                return ResourceManager.GetString("InfoMessageExecutionPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Resuming execution..
        /// </summary>
        internal static string InfoMessageExecutionResumed {
            get {
                return ResourceManager.GetString("InfoMessageExecutionResumed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File name : &quot;{0}&quot; already exists..
        /// </summary>
        internal static string InfoMessageFileExists {
            get {
                return ResourceManager.GetString("InfoMessageFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image found.
        /// </summary>
        internal static string InfoMessageImageFound {
            get {
                return ResourceManager.GetString("InfoMessageImageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image found at coordinates: {0}.
        /// </summary>
        internal static string InfoMessageImageFoundAtCoords {
            get {
                return ResourceManager.GetString("InfoMessageImageFoundAtCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image found at coordinates: {0} in {1} ms..
        /// </summary>
        internal static string InfoMessageImageFoundAtCoordsIn {
            get {
                return ResourceManager.GetString("InfoMessageImageFoundAtCoordsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image not found.
        /// </summary>
        internal static string InfoMessageImageNotFound {
            get {
                return ResourceManager.GetString("InfoMessageImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image search timed out after {0} ms..
        /// </summary>
        internal static string InfoMessageImageSearchTimeOut {
            get {
                return ResourceManager.GetString("InfoMessageImageSearchTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Program ready to use.
        /// </summary>
        internal static string InfoMessageProgramReady {
            get {
                return ResourceManager.GetString("InfoMessageProgramReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Searching for image... {0} ms elapsed..
        /// </summary>
        internal static string InfoMessageSearchingImageFor {
            get {
                return ResourceManager.GetString("InfoMessageSearchingImageFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Starting execution..
        /// </summary>
        internal static string InfoMessageStartingExecution {
            get {
                return ResourceManager.GetString("InfoMessageStartingExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Waiting for {0} ms..
        /// </summary>
        internal static string InfoMessageWaitActionWaitingTime {
            get {
                return ResourceManager.GetString("InfoMessageWaitActionWaitingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key.
        /// </summary>
        internal static string KeyActionName {
            get {
                return ResourceManager.GetString("KeyActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key : {0}.
        /// </summary>
        internal static string KeyActionToString {
            get {
                return ResourceManager.GetString("KeyActionToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alt.
        /// </summary>
        internal static string KeysAlt {
            get {
                return ResourceManager.GetString("KeysAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Backspace.
        /// </summary>
        internal static string KeysBackspace {
            get {
                return ResourceManager.GetString("KeysBackspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CapsLock.
        /// </summary>
        internal static string KeysCapsLock {
            get {
                return ResourceManager.GetString("KeysCapsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ctrl.
        /// </summary>
        internal static string KeysCtrl {
            get {
                return ResourceManager.GetString("KeysCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Del.
        /// </summary>
        internal static string KeysDelete {
            get {
                return ResourceManager.GetString("KeysDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Down.
        /// </summary>
        internal static string KeysDown {
            get {
                return ResourceManager.GetString("KeysDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End.
        /// </summary>
        internal static string KeysEnd {
            get {
                return ResourceManager.GetString("KeysEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter.
        /// </summary>
        internal static string KeysEnter {
            get {
                return ResourceManager.GetString("KeysEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Escape.
        /// </summary>
        internal static string KeysEscape {
            get {
                return ResourceManager.GetString("KeysEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left.
        /// </summary>
        internal static string KeysLeft {
            get {
                return ResourceManager.GetString("KeysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right.
        /// </summary>
        internal static string KeysRight {
            get {
                return ResourceManager.GetString("KeysRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shift.
        /// </summary>
        internal static string KeysShift {
            get {
                return ResourceManager.GetString("KeysShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Space.
        /// </summary>
        internal static string KeysSpace {
            get {
                return ResourceManager.GetString("KeysSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Up.
        /// </summary>
        internal static string KeysUp {
            get {
                return ResourceManager.GetString("KeysUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action if image found.
        /// </summary>
        internal static string LabelActionIfImageFound {
            get {
                return ResourceManager.GetString("LabelActionIfImageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action if image not found.
        /// </summary>
        internal static string LabelActionIfImageNotFound {
            get {
                return ResourceManager.GetString("LabelActionIfImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click duration.
        /// </summary>
        internal static string LabelClickDuration {
            get {
                return ResourceManager.GetString("LabelClickDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click type.
        /// </summary>
        internal static string LabelClickType {
            get {
                return ResourceManager.GetString("LabelClickType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinates.
        /// </summary>
        internal static string LabelCoordinates {
            get {
                return ResourceManager.GetString("LabelCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double click.
        /// </summary>
        internal static string LabelDoubleClick {
            get {
                return ResourceManager.GetString("LabelDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag and Drop.
        /// </summary>
        internal static string LabelDragAndDrop {
            get {
                return ResourceManager.GetString("LabelDragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End coordinates.
        /// </summary>
        internal static string LabelEndCoordinates {
            get {
                return ResourceManager.GetString("LabelEndCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expiration (s).
        /// </summary>
        internal static string LabelExpiration {
            get {
                return ResourceManager.GetString("LabelExpiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key.
        /// </summary>
        internal static string LabelKey {
            get {
                return ResourceManager.GetString("LabelKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left click.
        /// </summary>
        internal static string LabelLeftClick {
            get {
                return ResourceManager.GetString("LabelLeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait maximum (ms).
        /// </summary>
        internal static string LabelMaximumWait {
            get {
                return ResourceManager.GetString("LabelMaximumWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Middle click.
        /// </summary>
        internal static string LabelMiddleClick {
            get {
                return ResourceManager.GetString("LabelMiddleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait minimum (ms).
        /// </summary>
        internal static string LabelMinimumWait {
            get {
                return ResourceManager.GetString("LabelMinimumWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Move.
        /// </summary>
        internal static string LabelNoClick {
            get {
                return ResourceManager.GetString("LabelNoClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No image selected.
        /// </summary>
        internal static string LabelNoImageSelected {
            get {
                return ResourceManager.GetString("LabelNoImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Randomize interval.
        /// </summary>
        internal static string LabelRandomizeWait {
            get {
                return ResourceManager.GetString("LabelRandomizeWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repeat count.
        /// </summary>
        internal static string LabelRepeatCount {
            get {
                return ResourceManager.GetString("LabelRepeatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right click.
        /// </summary>
        internal static string LabelRightClick {
            get {
                return ResourceManager.GetString("LabelRightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scroll.
        /// </summary>
        internal static string LabelScroll {
            get {
                return ResourceManager.GetString("LabelScroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scroll amount.
        /// </summary>
        internal static string LabelScrollAmount {
            get {
                return ResourceManager.GetString("LabelScrollAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence.
        /// </summary>
        internal static string LabelSequence {
            get {
                return ResourceManager.GetString("LabelSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speed.
        /// </summary>
        internal static string LabelSpeed {
            get {
                return ResourceManager.GetString("LabelSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start coordinates.
        /// </summary>
        internal static string LabelStartCoordinates {
            get {
                return ResourceManager.GetString("LabelStartCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text to type.
        /// </summary>
        internal static string LabelTextToType {
            get {
                return ResourceManager.GetString("LabelTextToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Threshold.
        /// </summary>
        internal static string LabelThreshold {
            get {
                return ResourceManager.GetString("LabelThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Typing speed.
        /// </summary>
        internal static string LabelTypingSpeed {
            get {
                return ResourceManager.GetString("LabelTypingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use current position.
        /// </summary>
        internal static string LabelUseCurrentPosition {
            get {
                return ResourceManager.GetString("LabelUseCurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use image coordinates.
        /// </summary>
        internal static string LabelUseImageCoordinates {
            get {
                return ResourceManager.GetString("LabelUseImageCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait (ms).
        /// </summary>
        internal static string LabelWait {
            get {
                return ResourceManager.GetString("LabelWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bot.
        /// </summary>
        internal static string MenuBot {
            get {
                return ResourceManager.GetString("MenuBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        internal static string MenuBotStart {
            get {
                return ResourceManager.GetString("MenuBotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string MenuBotStop {
            get {
                return ResourceManager.GetString("MenuBotStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        internal static string MenuFileNew {
            get {
                return ResourceManager.GetString("MenuFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save as ....
        /// </summary>
        internal static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string MenuSettingsLanguage {
            get {
                return ResourceManager.GetString("MenuSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save logs.
        /// </summary>
        internal static string MenuSettingsSaveLogs {
            get {
                return ResourceManager.GetString("MenuSettingsSaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hotkeys.
        /// </summary>
        internal static string MenuSettingsShortcuts {
            get {
                return ResourceManager.GetString("MenuSettingsShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme.
        /// </summary>
        internal static string MenuSettingsTheme {
            get {
                return ResourceManager.GetString("MenuSettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Existing file.
        /// </summary>
        internal static string MessageCaptionFileExists {
            get {
                return ResourceManager.GetString("MessageCaptionFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mouse.
        /// </summary>
        internal static string MouseActionName {
            get {
                return ResourceManager.GetString("MouseActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à at coordinates.
        /// </summary>
        internal static string MouseActionToStringAtCoordinates {
            get {
                return ResourceManager.GetString("MouseActionToStringAtCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à at current position.
        /// </summary>
        internal static string MouseActionToStringAtCurrentPosition {
            get {
                return ResourceManager.GetString("MouseActionToStringAtCurrentPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à at image coordinates.
        /// </summary>
        internal static string MouseActionToStringAtImageCoordinates {
            get {
                return ResourceManager.GetString("MouseActionToStringAtImageCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double.
        /// </summary>
        internal static string MouseActionToStringDouble {
            get {
                return ResourceManager.GetString("MouseActionToStringDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag and Drop from {0} to {1}.
        /// </summary>
        internal static string MouseActionToStringDragAndDropFrom {
            get {
                return ResourceManager.GetString("MouseActionToStringDragAndDropFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scroll by : {0}.
        /// </summary>
        internal static string MouseActionToStringScrollBy {
            get {
                return ResourceManager.GetString("MouseActionToStringScrollBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you want to replace it ?.
        /// </summary>
        internal static string QuestionMessageReplace {
            get {
                return ResourceManager.GetString("QuestionMessageReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loop {0} of {1}.
        /// </summary>
        internal static string SequenceActionLoopNumber {
            get {
                return ResourceManager.GetString("SequenceActionLoopNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence.
        /// </summary>
        internal static string SequenceActionName {
            get {
                return ResourceManager.GetString("SequenceActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence : &quot;{0}&quot; x {1}.
        /// </summary>
        internal static string SequenceActionToString {
            get {
                return ResourceManager.GetString("SequenceActionToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text.
        /// </summary>
        internal static string TextActionName {
            get {
                return ResourceManager.GetString("TextActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Text to type : {0} | TypingSpeed: {1}.
        /// </summary>
        internal static string TextActionToString {
            get {
                return ResourceManager.GetString("TextActionToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait.
        /// </summary>
        internal static string WaitActionName {
            get {
                return ResourceManager.GetString("WaitActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait {0} ms.
        /// </summary>
        internal static string WaitActionToString {
            get {
                return ResourceManager.GetString("WaitActionToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait between {0} and {1} ms.
        /// </summary>
        internal static string WaitActionWithIntervalToString {
            get {
                return ResourceManager.GetString("WaitActionWithIntervalToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unsaved changes will be lost..
        /// </summary>
        internal static string WarningMessageUnsavedChanges {
            get {
                return ResourceManager.GetString("WarningMessageUnsavedChanges", resourceCulture);
            }
        }
    }
}
