//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tao_Bot_Maker.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tao_Bot_Maker.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Click button must be selected.
        /// </summary>
        internal static string action_ErrorMessage_ClickNotSelected {
            get {
                return ResourceManager.GetString("action_ErrorMessage_ClickNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Drag speed must be a number between 1 and 5.
        /// </summary>
        internal static string action_ErrorMessage_DragSpeedWrongInterval {
            get {
                return ResourceManager.GetString("action_ErrorMessage_DragSpeedWrongInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Expiration must be a number between -1 and 999999.
        /// </summary>
        internal static string action_ErrorMessage_ExpirationWrongInterval {
            get {
                return ResourceManager.GetString("action_ErrorMessage_ExpirationWrongInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Action &quot;If found&quot; must be selected.
        /// </summary>
        internal static string action_ErrorMessage_IfFound {
            get {
                return ResourceManager.GetString("action_ErrorMessage_IfFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Action &quot;If not found&quot; must be selected.
        /// </summary>
        internal static string action_ErrorMessage_IfNotFound {
            get {
                return ResourceManager.GetString("action_ErrorMessage_IfNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Image must be selected.
        /// </summary>
        internal static string action_ErrorMessage_ImageName {
            get {
                return ResourceManager.GetString("action_ErrorMessage_ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Coordinates must be a number between -999999 and 999999.
        /// </summary>
        internal static string action_ErrorMessage_InvalidCoords {
            get {
                return ResourceManager.GetString("action_ErrorMessage_InvalidCoords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Key must be entered.
        /// </summary>
        internal static string action_ErrorMessage_Key {
            get {
                return ResourceManager.GetString("action_ErrorMessage_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Repeat number must be between -1 and 999999.
        /// </summary>
        internal static string action_ErrorMessage_RepeatNumber {
            get {
                return ResourceManager.GetString("action_ErrorMessage_RepeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Sequence must be selected.
        /// </summary>
        internal static string action_ErrorMessage_SequenceName {
            get {
                return ResourceManager.GetString("action_ErrorMessage_SequenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error : Threshold must be a number between 0 and 255.
        /// </summary>
        internal static string action_ErrorMessage_ThresholdWrongInterval {
            get {
                return ResourceManager.GetString("action_ErrorMessage_ThresholdWrongInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click.
        /// </summary>
        internal static string action_Member_Click {
            get {
                return ResourceManager.GetString("action_Member_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag speed.
        /// </summary>
        internal static string action_Member_DragSpeed {
            get {
                return ResourceManager.GetString("action_Member_DragSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expiration.
        /// </summary>
        internal static string action_Member_Expiration {
            get {
                return ResourceManager.GetString("action_Member_Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action if found.
        /// </summary>
        internal static string action_Member_IfFound {
            get {
                return ResourceManager.GetString("action_Member_IfFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action if not found.
        /// </summary>
        internal static string action_Member_IfNotFound {
            get {
                return ResourceManager.GetString("action_Member_IfNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double click.
        /// </summary>
        internal static string action_Member_IsDoubleClick {
            get {
                return ResourceManager.GetString("action_Member_IsDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag.
        /// </summary>
        internal static string action_Member_IsDrag {
            get {
                return ResourceManager.GetString("action_Member_IsDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key.
        /// </summary>
        internal static string action_Member_Key {
            get {
                return ResourceManager.GetString("action_Member_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Picture name.
        /// </summary>
        internal static string action_Member_PictureName {
            get {
                return ResourceManager.GetString("action_Member_PictureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of repetitions.
        /// </summary>
        internal static string action_Member_RepeatNumber {
            get {
                return ResourceManager.GetString("action_Member_RepeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence.
        /// </summary>
        internal static string action_Member_Sequence {
            get {
                return ResourceManager.GetString("action_Member_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Threshold.
        /// </summary>
        internal static string action_Member_Threshold {
            get {
                return ResourceManager.GetString("action_Member_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X1.
        /// </summary>
        internal static string action_Member_X1 {
            get {
                return ResourceManager.GetString("action_Member_X1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X2.
        /// </summary>
        internal static string action_Member_X2 {
            get {
                return ResourceManager.GetString("action_Member_X2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y1.
        /// </summary>
        internal static string action_Member_Y1 {
            get {
                return ResourceManager.GetString("action_Member_Y1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Y2.
        /// </summary>
        internal static string action_Member_Y2 {
            get {
                return ResourceManager.GetString("action_Member_Y2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click.
        /// </summary>
        internal static string ActionName_Click {
            get {
                return ResourceManager.GetString("ActionName_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If picture.
        /// </summary>
        internal static string ActionName_IfPicture {
            get {
                return ResourceManager.GetString("ActionName_IfPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image search.
        /// </summary>
        internal static string ActionName_ImageSearch {
            get {
                return ResourceManager.GetString("ActionName_ImageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key.
        /// </summary>
        internal static string ActionName_Key {
            get {
                return ResourceManager.GetString("ActionName_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repeat sequence.
        /// </summary>
        internal static string ActionName_Loop {
            get {
                return ResourceManager.GetString("ActionName_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait for image.
        /// </summary>
        internal static string ActionName_PictureWait {
            get {
                return ResourceManager.GetString("ActionName_PictureWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence.
        /// </summary>
        internal static string ActionName_Sequence {
            get {
                return ResourceManager.GetString("ActionName_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown.
        /// </summary>
        internal static string ActionName_Unknown {
            get {
                return ResourceManager.GetString("ActionName_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait.
        /// </summary>
        internal static string ActionName_Wait {
            get {
                return ResourceManager.GetString("ActionName_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string button_Cancel {
            get {
                return ResourceManager.GetString("button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear area.
        /// </summary>
        internal static string button_ClearArea {
            get {
                return ResourceManager.GetString("button_ClearArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find image.
        /// </summary>
        internal static string button_FindImage {
            get {
                return ResourceManager.GetString("button_FindImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string button_OK {
            get {
                return ResourceManager.GetString("button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose image.
        /// </summary>
        internal static string button_Picture {
            get {
                return ResourceManager.GetString("button_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show area.
        /// </summary>
        internal static string button_ShowDrawingArea {
            get {
                return ResourceManager.GetString("button_ShowDrawingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alt.
        /// </summary>
        internal static string label_Alt {
            get {
                return ResourceManager.GetString("label_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ctrl.
        /// </summary>
        internal static string label_Ctrl {
            get {
                return ResourceManager.GetString("label_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Double click.
        /// </summary>
        internal static string label_DoubleClick {
            get {
                return ResourceManager.GetString("label_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag.
        /// </summary>
        internal static string label_Drag {
            get {
                return ResourceManager.GetString("label_Drag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Drag speed.
        /// </summary>
        internal static string label_DragSpeed {
            get {
                return ResourceManager.GetString("label_DragSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expiration (s).
        /// </summary>
        internal static string label_Expiration {
            get {
                return ResourceManager.GetString("label_Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key.
        /// </summary>
        internal static string label_Key {
            get {
                return ResourceManager.GetString("label_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left click.
        /// </summary>
        internal static string label_LeftClick {
            get {
                return ResourceManager.GetString("label_LeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Middle click.
        /// </summary>
        internal static string label_MiddleClick {
            get {
                return ResourceManager.GetString("label_MiddleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of repetitions.
        /// </summary>
        internal static string label_RepeatNumber {
            get {
                return ResourceManager.GetString("label_RepeatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right click.
        /// </summary>
        internal static string label_RightClick {
            get {
                return ResourceManager.GetString("label_RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence.
        /// </summary>
        internal static string label_Sequence {
            get {
                return ResourceManager.GetString("label_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If expired.
        /// </summary>
        internal static string label_SequenceIfExpired {
            get {
                return ResourceManager.GetString("label_SequenceIfExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If not found.
        /// </summary>
        internal static string label_SequenceIfNotFound {
            get {
                return ResourceManager.GetString("label_SequenceIfNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If found.
        /// </summary>
        internal static string label_SequenceIfPicture {
            get {
                return ResourceManager.GetString("label_SequenceIfPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set X Y at cursor position.
        /// </summary>
        internal static string label_SetXY {
            get {
                return ResourceManager.GetString("label_SetXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set X2 Y2 at cursor position.
        /// </summary>
        internal static string label_SetXY2 {
            get {
                return ResourceManager.GetString("label_SetXY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shift.
        /// </summary>
        internal static string label_Shift {
            get {
                return ResourceManager.GetString("label_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Bot.
        /// </summary>
        internal static string label_StartBot {
            get {
                return ResourceManager.GetString("label_StartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Bot.
        /// </summary>
        internal static string label_StopBot {
            get {
                return ResourceManager.GetString("label_StopBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Threshold.
        /// </summary>
        internal static string label_Threshold {
            get {
                return ResourceManager.GetString("label_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delay (ms).
        /// </summary>
        internal static string label_WaitTime {
            get {
                return ResourceManager.GetString("label_WaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action added : .
        /// </summary>
        internal static string log_ActionAdded {
            get {
                return ResourceManager.GetString("log_ActionAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action deleted :  .
        /// </summary>
        internal static string log_ActionDeleted {
            get {
                return ResourceManager.GetString("log_ActionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action edited : .
        /// </summary>
        internal static string log_ActionEdited {
            get {
                return ResourceManager.GetString("log_ActionEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ActionView dialog Add Mode opened.
        /// </summary>
        internal static string log_ActionView_AddMode {
            get {
                return ResourceManager.GetString("log_ActionView_AddMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ActionView dialog closed.
        /// </summary>
        internal static string log_ActionView_Closed {
            get {
                return ResourceManager.GetString("log_ActionView_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ActionView dialog Edit Mode opened.
        /// </summary>
        internal static string log_ActionView_EditMode {
            get {
                return ResourceManager.GetString("log_ActionView_EditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Panel selected : .
        /// </summary>
        internal static string log_ActionView_SelectedPanel {
            get {
                return ResourceManager.GetString("log_ActionView_SelectedPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application closed.
        /// </summary>
        internal static string log_ApplicationClosed {
            get {
                return ResourceManager.GetString("log_ApplicationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application ready to use.
        /// </summary>
        internal static string log_ApplicationInitialized {
            get {
                return ResourceManager.GetString("log_ApplicationInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme applied.
        /// </summary>
        internal static string log_AppliedTheme {
            get {
                return ResourceManager.GetString("log_AppliedTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DialogResult : CANCEL.
        /// </summary>
        internal static string log_DialogResult_Cancel {
            get {
                return ResourceManager.GetString("log_DialogResult_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DialogResult : NONE.
        /// </summary>
        internal static string log_DialogResult_None {
            get {
                return ResourceManager.GetString("log_DialogResult_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à DialogResult : OK.
        /// </summary>
        internal static string log_DialogResult_Ok {
            get {
                return ResourceManager.GetString("log_DialogResult_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Actions loaded.
        /// </summary>
        internal static string log_Loaded_Actions {
            get {
                return ResourceManager.GetString("log_Loaded_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading action : .
        /// </summary>
        internal static string log_Loading_Action {
            get {
                return ResourceManager.GetString("log_Loading_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading actions.
        /// </summary>
        internal static string log_Loading_Actions {
            get {
                return ResourceManager.GetString("log_Loading_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading sequence : .
        /// </summary>
        internal static string log_Loading_Sequence {
            get {
                return ResourceManager.GetString("log_Loading_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fail to load sequence : .
        /// </summary>
        internal static string log_Loading_Sequence_Fail {
            get {
                return ResourceManager.GetString("log_Loading_Sequence_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence loaded.
        /// </summary>
        internal static string log_Loading_Sequence_Success {
            get {
                return ResourceManager.GetString("log_Loading_Sequence_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Localization updated.
        /// </summary>
        internal static string log_LocalizationUpdated {
            get {
                return ResourceManager.GetString("log_LocalizationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence deleted : .
        /// </summary>
        internal static string log_Sequence_Deleted {
            get {
                return ResourceManager.GetString("log_Sequence_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence saved : .
        /// </summary>
        internal static string log_Sequence_Saved {
            get {
                return ResourceManager.GetString("log_Sequence_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Setting language to :  .
        /// </summary>
        internal static string log_SettingLanguage {
            get {
                return ResourceManager.GetString("log_SettingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Setting &quot;SaveLog&quot; value : .
        /// </summary>
        internal static string log_SettingSavelogs {
            get {
                return ResourceManager.GetString("log_SettingSavelogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Bot&quot; button state updated : .
        /// </summary>
        internal static string log_UpdateButtonState_Bot {
            get {
                return ResourceManager.GetString("log_UpdateButtonState_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Delete&quot; button state updated : .
        /// </summary>
        internal static string log_UpdateButtonState_DeleteAction {
            get {
                return ResourceManager.GetString("log_UpdateButtonState_DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Delete sequence&quot; button state updated : .
        /// </summary>
        internal static string log_UpdateButtonState_DeleteSequence {
            get {
                return ResourceManager.GetString("log_UpdateButtonState_DeleteSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Edit&quot; button state updated : .
        /// </summary>
        internal static string log_UpdateButtonState_Edit {
            get {
                return ResourceManager.GetString("log_UpdateButtonState_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Hotkey&quot; button updated.
        /// </summary>
        internal static string log_UpdateButtonState_Hotkey {
            get {
                return ResourceManager.GetString("log_UpdateButtonState_Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Language&quot; button state updated : .
        /// </summary>
        internal static string log_UpdateButtonState_Language {
            get {
                return ResourceManager.GetString("log_UpdateButtonState_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Savelogs&quot; button state updated : .
        /// </summary>
        internal static string log_UpdateButtonState_SaveLogs {
            get {
                return ResourceManager.GetString("log_UpdateButtonState_SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;Theme&quot; button state updated : .
        /// </summary>
        internal static string log_UpdateButtonState_Theme {
            get {
                return ResourceManager.GetString("log_UpdateButtonState_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace image ?.
        /// </summary>
        internal static string MessageBox_ImageAlreadyInFolder_Caption {
            get {
                return ResourceManager.GetString("MessageBox_ImageAlreadyInFolder_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à is already present in Pictures folder.
        ///Do you want to replace it ?
        ///
        ///Yes : Image will be replaced.
        ///No : Image will be imported with a new name..
        /// </summary>
        internal static string MessageBox_ImageAlreadyInFolder_Message {
            get {
                return ResourceManager.GetString("MessageBox_ImageAlreadyInFolder_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image found at coords : .
        /// </summary>
        internal static string MessageBox_ImageFound {
            get {
                return ResourceManager.GetString("MessageBox_ImageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image not found.
        /// </summary>
        internal static string MessageBox_ImageNotFound {
            get {
                return ResourceManager.GetString("MessageBox_ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : This will delete the sequence entirely.
        ///Do you want to proceed ?.
        /// </summary>
        internal static string MessageBox_WarningDeleteSequence {
            get {
                return ResourceManager.GetString("MessageBox_WarningDeleteSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning : Unsaved changes will be lost.
        ///Do you want to exit ?.
        /// </summary>
        internal static string MessageBox_WarningSequenceNotSaved {
            get {
                return ResourceManager.GetString("MessageBox_WarningSequenceNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New sequence.
        /// </summary>
        internal static string tab_NewSequence {
            get {
                return ResourceManager.GetString("tab_NewSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace sequence.
        /// </summary>
        internal static string tab_ReplaceSequence {
            get {
                return ResourceManager.GetString("tab_ReplaceSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hotkeys.
        /// </summary>
        internal static string title_Hotkeys {
            get {
                return ResourceManager.GetString("title_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        internal static string title_NewActionDialog {
            get {
                return ResourceManager.GetString("title_NewActionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save sequence.
        /// </summary>
        internal static string title_SaveSequenceDialog {
            get {
                return ResourceManager.GetString("title_SaveSequenceDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add action.
        /// </summary>
        internal static string toolTip_Button_AddAction {
            get {
                return ResourceManager.GetString("toolTip_Button_AddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete selected action.
        /// </summary>
        internal static string toolTip_Button_DeleteAction {
            get {
                return ResourceManager.GetString("toolTip_Button_DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete sequence.
        /// </summary>
        internal static string toolTip_Button_DeleteSequence {
            get {
                return ResourceManager.GetString("toolTip_Button_DeleteSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit selected action.
        /// </summary>
        internal static string toolTip_Button_EditAction {
            get {
                return ResourceManager.GetString("toolTip_Button_EditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save sequence.
        /// </summary>
        internal static string toolTip_Button_SaveSequence {
            get {
                return ResourceManager.GetString("toolTip_Button_SaveSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Bot.
        /// </summary>
        internal static string toolTip_Button_StartBot {
            get {
                return ResourceManager.GetString("toolTip_Button_StartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Bot.
        /// </summary>
        internal static string toolTip_Button_StopBot {
            get {
                return ResourceManager.GetString("toolTip_Button_StopBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        internal static string tsm_About {
            get {
                return ResourceManager.GetString("tsm_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bot.
        /// </summary>
        internal static string tsm_Bot {
            get {
                return ResourceManager.GetString("tsm_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        internal static string tsm_Bot_Start {
            get {
                return ResourceManager.GetString("tsm_Bot_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string tsm_Bot_Stop {
            get {
                return ResourceManager.GetString("tsm_Bot_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string tsm_File {
            get {
                return ResourceManager.GetString("tsm_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string tsm_File_Exit {
            get {
                return ResourceManager.GetString("tsm_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        internal static string tsm_File_New {
            get {
                return ResourceManager.GetString("tsm_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string tsm_File_Save {
            get {
                return ResourceManager.GetString("tsm_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save as ....
        /// </summary>
        internal static string tsm_File_SaveAs {
            get {
                return ResourceManager.GetString("tsm_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string tsm_Settings {
            get {
                return ResourceManager.GetString("tsm_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string tsm_Settings_Language {
            get {
                return ResourceManager.GetString("tsm_Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save logs.
        /// </summary>
        internal static string tsm_Settings_SaveLogs {
            get {
                return ResourceManager.GetString("tsm_Settings_SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hotkeys.
        /// </summary>
        internal static string tsm_Settings_Shortcuts {
            get {
                return ResourceManager.GetString("tsm_Settings_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme.
        /// </summary>
        internal static string tsm_Settings_Theme {
            get {
                return ResourceManager.GetString("tsm_Settings_Theme", resourceCulture);
            }
        }
    }
}
