//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tao_Bot_Maker.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tao_Bot_Maker.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Click.
        /// </summary>
        internal static string ActionName_Click {
            get {
                return ResourceManager.GetString("ActionName_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If picture.
        /// </summary>
        internal static string ActionName_IfPicture {
            get {
                return ResourceManager.GetString("ActionName_IfPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Image search.
        /// </summary>
        internal static string ActionName_ImageSearch {
            get {
                return ResourceManager.GetString("ActionName_ImageSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key.
        /// </summary>
        internal static string ActionName_Key {
            get {
                return ResourceManager.GetString("ActionName_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repeat sequence.
        /// </summary>
        internal static string ActionName_Loop {
            get {
                return ResourceManager.GetString("ActionName_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait for image.
        /// </summary>
        internal static string ActionName_PictureWait {
            get {
                return ResourceManager.GetString("ActionName_PictureWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence.
        /// </summary>
        internal static string ActionName_Sequence {
            get {
                return ResourceManager.GetString("ActionName_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown.
        /// </summary>
        internal static string ActionName_Unknown {
            get {
                return ResourceManager.GetString("ActionName_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wait.
        /// </summary>
        internal static string ActionName_Wait {
            get {
                return ResourceManager.GetString("ActionName_Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string button_Cancel {
            get {
                return ResourceManager.GetString("button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear area.
        /// </summary>
        internal static string button_ClearZone {
            get {
                return ResourceManager.GetString("button_ClearZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find image.
        /// </summary>
        internal static string button_FindImage {
            get {
                return ResourceManager.GetString("button_FindImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string button_OK {
            get {
                return ResourceManager.GetString("button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose image.
        /// </summary>
        internal static string button_Picture {
            get {
                return ResourceManager.GetString("button_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show area.
        /// </summary>
        internal static string button_ShowDrawingArea {
            get {
                return ResourceManager.GetString("button_ShowDrawingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alt.
        /// </summary>
        internal static string label_Alt {
            get {
                return ResourceManager.GetString("label_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ctrl.
        /// </summary>
        internal static string label_Ctrl {
            get {
                return ResourceManager.GetString("label_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key.
        /// </summary>
        internal static string label_Key {
            get {
                return ResourceManager.GetString("label_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left click.
        /// </summary>
        internal static string label_LeftClick {
            get {
                return ResourceManager.GetString("label_LeftClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Number of repetitions.
        /// </summary>
        internal static string label_RepetitionNumber {
            get {
                return ResourceManager.GetString("label_RepetitionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right click.
        /// </summary>
        internal static string label_RightClick {
            get {
                return ResourceManager.GetString("label_RightClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence.
        /// </summary>
        internal static string label_Sequence {
            get {
                return ResourceManager.GetString("label_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence if expired.
        /// </summary>
        internal static string label_SequenceIfExpired {
            get {
                return ResourceManager.GetString("label_SequenceIfExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence if not found.
        /// </summary>
        internal static string label_SequenceIfNotFound {
            get {
                return ResourceManager.GetString("label_SequenceIfNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sequence if found.
        /// </summary>
        internal static string label_SequenceIfPicture {
            get {
                return ResourceManager.GetString("label_SequenceIfPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set X Y at cursor position.
        /// </summary>
        internal static string label_SetXY {
            get {
                return ResourceManager.GetString("label_SetXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set X2 Y2 at cursor position.
        /// </summary>
        internal static string label_SetXY2 {
            get {
                return ResourceManager.GetString("label_SetXY2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shift.
        /// </summary>
        internal static string label_Shift {
            get {
                return ResourceManager.GetString("label_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Bot.
        /// </summary>
        internal static string label_StartBot {
            get {
                return ResourceManager.GetString("label_StartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Bot.
        /// </summary>
        internal static string label_StopBot {
            get {
                return ResourceManager.GetString("label_StopBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Threshold.
        /// </summary>
        internal static string label_Threshold {
            get {
                return ResourceManager.GetString("label_Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delay (ms).
        /// </summary>
        internal static string label_WaitTime {
            get {
                return ResourceManager.GetString("label_WaitTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New sequence.
        /// </summary>
        internal static string tab_NewSequence {
            get {
                return ResourceManager.GetString("tab_NewSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Replace sequence.
        /// </summary>
        internal static string tab_ReplaceSequence {
            get {
                return ResourceManager.GetString("tab_ReplaceSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hotkeys.
        /// </summary>
        internal static string title_Hotkeys {
            get {
                return ResourceManager.GetString("title_Hotkeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Action.
        /// </summary>
        internal static string title_NewActionDialog {
            get {
                return ResourceManager.GetString("title_NewActionDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save sequence.
        /// </summary>
        internal static string title_SaveSequenceDialog {
            get {
                return ResourceManager.GetString("title_SaveSequenceDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add action.
        /// </summary>
        internal static string toolTip_Button_AddAction {
            get {
                return ResourceManager.GetString("toolTip_Button_AddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete selected action.
        /// </summary>
        internal static string toolTip_Button_DeleteAction {
            get {
                return ResourceManager.GetString("toolTip_Button_DeleteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete sequence.
        /// </summary>
        internal static string toolTip_Button_DeleteSequence {
            get {
                return ResourceManager.GetString("toolTip_Button_DeleteSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit selected action.
        /// </summary>
        internal static string toolTip_Button_EditAction {
            get {
                return ResourceManager.GetString("toolTip_Button_EditAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save sequence.
        /// </summary>
        internal static string toolTip_Button_SaveSequence {
            get {
                return ResourceManager.GetString("toolTip_Button_SaveSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Bot.
        /// </summary>
        internal static string toolTip_Button_StartBot {
            get {
                return ResourceManager.GetString("toolTip_Button_StartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop Bot.
        /// </summary>
        internal static string toolTip_Button_StopBot {
            get {
                return ResourceManager.GetString("toolTip_Button_StopBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        internal static string tsm_About {
            get {
                return ResourceManager.GetString("tsm_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bot.
        /// </summary>
        internal static string tsm_Bot {
            get {
                return ResourceManager.GetString("tsm_Bot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        internal static string tsm_Bot_Start {
            get {
                return ResourceManager.GetString("tsm_Bot_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string tsm_Bot_Stop {
            get {
                return ResourceManager.GetString("tsm_Bot_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string tsm_File {
            get {
                return ResourceManager.GetString("tsm_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string tsm_File_Exit {
            get {
                return ResourceManager.GetString("tsm_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        internal static string tsm_File_New {
            get {
                return ResourceManager.GetString("tsm_File_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        internal static string tsm_File_Save {
            get {
                return ResourceManager.GetString("tsm_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save as ....
        /// </summary>
        internal static string tsm_File_SaveAs {
            get {
                return ResourceManager.GetString("tsm_File_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string tsm_Settings {
            get {
                return ResourceManager.GetString("tsm_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        internal static string tsm_Settings_Language {
            get {
                return ResourceManager.GetString("tsm_Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save logs.
        /// </summary>
        internal static string tsm_Settings_SaveLogs {
            get {
                return ResourceManager.GetString("tsm_Settings_SaveLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hotkeys.
        /// </summary>
        internal static string tsm_Settings_Shortcuts {
            get {
                return ResourceManager.GetString("tsm_Settings_Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme.
        /// </summary>
        internal static string tsm_Settings_Theme {
            get {
                return ResourceManager.GetString("tsm_Settings_Theme", resourceCulture);
            }
        }
    }
}
